jobs:
  - name: publicci-test_runCI
    type: runCI
    steps:
      - IN: publicci-test_ciRepo
      - OUT: param-1

  - name: test
    type: runSh
    on_start:
          - script: echo 'This block executes when the TASK starts'
    steps:
      - IN: param-1
      - TASK:
        - script: ls -lah